### ISSUE TITLE
Where are time units actually used?

### ISSUE THREAD

**Issue by isaacsanders** [bryannaegele/telemetry_metrics_prometheus_core#2]
I have scoured this repo, and it is not used.

**Comment by isaacsanders** [comment]
I had been under the impression that Telemetry.Metrics did nothing, but it seems to do the conversion. Thanks

**Comment by bryannaegele** [comment]
Yep, it actually does stuff! 

Metrics generates a utility function under the hood that automatically does time conversions when they're in the definition so that every reporter didn't have to reimplement that code. We only do that for time conversions though, so if you ever need to do memory size conversions, that requires a custom function, e.g. kilobytes to bytes.
